const types = {};
types.GET_PROCESS_IDS = 'GET_PROCESS_IDS';
types.GET_PROCESS_AUDITORS = 'GET_PROCESS_AUDITORS';
types.GET_PROCESS_LIST_DETAIL = 'GET_PROCESS_LIST_DETAIL';
types.UPDATE_PROCESS_STATUS = 'UPDATE_PROCESS_STATUS';

export default types;
