const types = {};
types.GET_CATALOG_LINKS = 'GET_CATALOG_LINKS';
types.GET_PROCESS_AUDITORS = 'GET_PROCESS_AUDITORS';
types.GET_PROCESS_LIST_DETAIL = 'GET_PROCESS_LIST_DETAIL';
types.UPDATE_PROCESS_STATUS = 'UPDATE_PROCESS_STATUS';

// 首页状态
types.GET_HOME_CONSUMER = 'GET_HOME_CONSUMER';
types.GET_SECURE_DATA = 'GET_SECURE_DATA';
types.GET_CONSUMER_DATA = 'GET_CONSUMER_DATA';

export default types;
